name: Build Windows Executable (ok-ww-e)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build exe with launcher
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: 'UTF-8'

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Configure git
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          echo "action_state=yellow" >> $env:GITHUB_ENV
          echo "${{ env.action_state }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set UTF-8 encoding
        run: |
          set PYTHONIOENCODING=utf-8
          set PYTHONLEGACYWINDOWSSTDIO=utf-8
          echo PYTHONIOENCODING=utf-8 >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: inline_ok_requirements
        run: |
          python -m ok.update.inline_ok_requirements --tag ${{ github.ref_name }}

      - name: Run tests
        run: |
          Get-ChildItem -Path ".\tests\*.py" | ForEach-Object {
              Write-Host "Running tests in $($_.FullName)"
              try {
                  # Run the Python unittest command
                  python -m unittest $_.FullName

                  # Check if the previous command succeeded
                  if ($LASTEXITCODE -ne 0) {
                      throw "Tests failed in $($_.FullName)"
                  }
              } catch {
                  # Stop the loop and return the error
                  Write-Error $_
                  exit 1
              }
          }

      - name: Sync Repositories
        id: sync
        uses: ok-oldking/partial-sync-repo@master
        with:
          repos: |
            https://${{ github.repository_owner }}:${{ secrets._GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/ok-ww-e
          sync_list: 'deploy.txt'
          tag: ${{ github.ref_name }}
          gitignore_file: '.update_repo_gitignore'
          show_author: true

      - name: pyappify build-exe-only
        id: build-exe-only
        uses: ok-oldking/pyappify-action@master
        with:
          build_exe_only: false

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ### 更新日志 ${{ steps.sync.outputs.start_tag }} -> ${{ steps.sync.outputs.end_tag }}
              ${{ steps.sync.outputs.changes_with_asterisk }}
            ### 下载说明
              * ok-ww-win32-online-setup.exe 在线安装包, 在线白嫖的服务器不一定稳定, 建议优先使用完整包.
              * ok-ww-win32-Global-setup.exe full package with dependencies, using GitHub and PyPi as update source
              * 不要下载ok-ww-win32.zip,和SourceCode.zip, Do Not Download the SourceCode, ok-ww-win32.zip
          draft: false
          prerelease: false
          files: pyappify_dist/*
